apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
  name: istiod-istio-system
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - '*'
