apiVersion: "rbac.istio.io/v1alph1"
kind: ServiceRoleBinding
metadata:
  name: test-binding-products
  namespace: default
spec:
  subjects:
  - user: "service-account-a"
  - user: "istio-ingress-service-account"
    properties:
     request.auth.claims[email]: "a@foo.com"
  roleRef:
    kind: ServiceRole
    name: "prodicts-viewer"
